services: 
  database:
    container_name: warrior-foot-pg
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: warrior_foot
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
